[package]
name = "ws-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ws-api = { git = "ssh://git@github.com/spiralblue/ws-api.git", version = "0.1.0" }
